/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.common.exception;

/**
 * ``
 *
 * @author Michael
 */
public interface ErrorConstants {

    /**
     * school calendar error
     */
    String CONFLICTING_TERM_DATES = "ERROR_CONFLICTING_TERM_DATES";
    String OVERLAPPING_PREVIOUS_SCHOOL_YEARS = "ERROR_OVERLAPPING_PREVIOUS_SCHOOL_YEARS";
    String OUT_OF_YEAR_DATE_BOUNDARIES = "ERROR_OUT_OF_YEAR_DATE_BOUNDARIES";
    String OVERLAPPING_START_DATE = "ERROR_OVERLAPPING_START_DATE";
    String NO_CURRENT_YEAR_SET = "ERROR_NO_CURRENT_YEAR_SET";
    String DUPLICATION_DETECTED = "ERROR_DUPLICATION_DETECTED";
    /**
     *
     */
    String NO_SCHOOL_PREF_SETTINGS = "ERROR_NO_SCHOOL_PREF_SETTINGS";
    String NO_REGISTERED_CLASS = "ERROR_NO_REGISTERED_CLASS";
    String CANNOT_DELETE_ASSIGNMENT = "ERROR_CANNOT_DELETE_ASSIGNMENT_STATUS_HAS_CHANGED";
    String ERROR_NO_CRITERIA_SET = "ERROR_NO_CRITERIA_SET";
    String ERROR_FILE_NOT_FOUND = "ERROR_FILE_NOT_FOUND";
    String ERROR_MESSAGE_UNIQUE_EMAIL = "ERROR_MESSAGE_UNIQUE_EMAIL";
    String ERROR_MESSAGE_UNIQUE_UNAME = "ERROR_MESSAGE_UNIQUE_UNAME";
    String OBJ_DOES_NOT_EXIST = "ERROR_OBJ_DOES_NOT_EXIST";
    String SCHOOL_EMAIL_ALREADY_EXIST = "ERROR_SCHOOL_EMAIL_ALREADY_EXIST";
    String SCHOOL_NAME_CITY_ALREADY_EXIST = "ERROR_SCHOOL_NAME_CITY_ALREADY_EXIST";
    String EMPLOYEE_ALREADY_EXIST = "ERROR_EMPLOYEE_ALREADY_EXIST";
    String INVALID_USERNAME = "ERROR_INVALID_USERNAME";
    String INVALID_PASSWORD = "ERROR_INVALID_PASSWORD";
    String ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL";
    String INVALID_PHONE_NUMBER = "ERROR_INVALID_PHONE_NUMBER";
    String INVALID_OPERATION = "ERROR_INVALID_OPERATION";
    String CLASS_WITH_CODE_ALREADY_EXIST = "ERROR_CLASS_WITH_CODE_ALREADY_EXIST";
    String NO_NATIONAL_AFFILIATION = "ERROR_NO_NATIONAL_AFFILIATION";
    String ERROR_CODE_ALREADY_EXISTS = "ERROR_CODE_ALREADY_EXISTS";
    String ERROR_DESC_ALREADY_EXISTS = "ERROR_DESCRIPTION_ALREADY_EXISTS";
    String DUPLICATE_ALBUM = "ERROR_DUPLICATE_ALBUM";
    String INVALID_SUBJECT = "ERROR_INVALID_SUBJECT";
    String INVALID_GRADE_LEVEL = "ERROR_INVALID_GRADE_LEVEL";
    String DUPLICATE_CLASS_TEACHER_ALLOC = "ERROR_DUPLICATE_CLASS_TEACHER_ALLOCATION";
    String DUPLICATE_DUPLICATE_SUBJECT_CODE = "ERROR_DUPLICATE_SUBJECT_CODE";
    String DUPLICATE_GRADE_SUBJECT = "ERROR_DUPLICATE_GRADE_SUBJECT";
    String DUPLICATE_SUBJECT_TEACHER = "ERROR_DUPLICATE_SUBJECT_TEACHER";
    String DUPLICATE_SCHOOL_SECTION = "ERROR_DUPLICATE_SCHOOL_SECTION";
    String DUPLICATE_SCHOOL_CLUB = "ERROR_DUPLICATE_SCHOOL_CLUB";
    String INVALID_PARTICIPANT_CODE = "ERROR_INVALID_PARTICIPANT_CODE";
    String INVALID_ASSIGNMENT_STATE = "ERROR_INVALID_ASSIGNMENT_STATE";
    String SCORES_NOT_AVAILABLE_FOR_SAVING = "ERROR_SCORES_NOT_AVAILABLE_FOR_SAVING";
    String CANNOT_FIND_ASSIGNMENT = "ERROR_CANNOT_FIND_ASSIGNMENT";
    String SCORE_SHEET_ALREADY_PREPARED = "ERROR_SCORE_SHEET_ALREADY_PREPARED";
    String EXAM_ALREADY_COMMITTED = "ERROR_EXAM_ALREADY_COMMITTED";
    String TERM_FINAL_EXAM_ALREADY_EXISTS = "ERROR_TERM_FINAL_EXAM_ALREADY_EXISTS";
    String DUPLICATE_TERM_EXAM = "ERROR_DUPLICATE_TERM_EXAM";
    String INVALID_DATE_ADJUSTMENT = "ERROR_INVALID_DATE_ADJUSTMENT";
    String INVALID_EXAM_DATE = "ERROR_EXAM_DATE_IS_BEFORE_EXAM_BATCH_START_DATE";
    String INVALID_EXAM_TYPE = "ERROR_INVALID_EXAM_TYPE";
    String CANNOT_FIND_EXAM = "ERROR_CANNOT_FIND_EXAM";
    String EXAMSCORE_NOT_AVAILABLE_FOR_SAVING = "ERROR_EXAMSCORE_NOT_AVAILABLE_FOR_SAVING";
    String INVALID_EXAM_BATCH_STATE = "ERROR_INVALID_EXAM_BATCH_STATE";
    String INVALID_EXAM_BATCH_CLASS_STATE = "ERROR_INVALID_EXAM_BATCH_CLASS_STATE";
    String SCHOOL_CLASS_NOT_EMPTY = "ERROR_SCHOOL_CLASS_NOT_EMPTY";
    /**
     * store error constants
     */
    String STORE_ALREADY_EXIST = "ERROR_STORE_ALREADY_EXIST";
    String NULL_ITEM_QUANTITY = "ERROR_NULL_ITEM_QUANTITY";
    String DUPLICATE_STORE_ITEM_NAME = "ERROR_DUPLICATE_STORE_ITEM_NAME";
    String CANNOT_FIND_ITEM = "ERROR_CANNOT_FIND_ITEM";
    String OUT_OF_STOCK = "ERROR_OUT_OF_STOCK";
    /**
     * txn journal error constants
     */
    String NO_ACCT_SPECIFIED = "ERROR_NO_ACCT_SPECIFIED";
    /**
     * finance setup error constants
     */
    String CODE_ALREADY_IN_USE = "ERROR_CODE_ALREADY_IN_USE";
    String DUPLICATE_SCHOOL_GRADE_TYPE = "ERROR_DUPLICATE_SCHOOL_GRADE_TYPE";
    String DUPLICATE_APPLICATION_FOR_TYPE = "ERROR_DUPLICATE_APPLICATION_FOR_TYPE";
    String NO_ITEM_SELECTED = "ERROR_NO_ITEM_SELECTED";
    String NEITHER_ACCOUNTS_SPECIFIED = "ERROR_NEITHER_ACCOUNTS_SPECIFIED";
    /**
     * finance service error constants
     */
    String INVALID_RECEIPT = "ERROR_INVALID_RECEIPT";
    String RECEIPT_ALREADY_USED = "ERROR_RECEIPT_ALREADY_USED";
    String RECORD_ALREADY_REVERSED = "ERROR_RECORD_ALREADY_REVERSED";
    String RECEIPT_VAL_ALREADY_UTILIZED = "ERROR_RECEIPT_VAL_ALREADY_UTILIZED";
    String FEE_ALREADY_PAID = "ERROR_FEE_ALREADY_PAID";
    String CANNOT_REVERSE_A_REVERSAL = "ERROR_CANNOT_REVERSE_A_REVERSAL";
    String NO_PAY_STRUCTURE_EMPLOYEE = "ERROR_NO_PAY_STRUCTURE_EMPLOYEE";
    String CANNOT_FIND_PAYROLL = "ERROR_CANNOT_FIND_PAYROLL";
    String PAYROLL_ALREADY_APPROVED = "ERROR_PAYROLL_ALREADY_APPROVED";
    String PAYROLL_FOR_MONTH_EXISTS = "ERROR_PAYROLL_FOR_MONTH_EXISTS";
    /**
     * student service error constants
     */
    String CANNOT_FIND_STUDENT = "ERROR_CANNOT_FIND_STUDENT";
    String CANNOT_REPLACE_RELATIONSHIP = "ERROR_CANNOT_REPLACE_RELATIONSHIP";
    String CANNOT_FIND_PARENT = "ERROR_CANNOT_FIND_PARENT";
    String CANNOT_REPLACE_NULL_RELATIONSHIP = "ERROR_REPLACE_NULL_RELATIONSHIP";
}
